version: "3.7"
name: "quarto"
services:
  quarto:
    build:
      context: ./.docker
      dockerfile: Dockerfile-quarto
    image: bosa/quarto
    hostname: quarto-render
    container_name: quarto-render
    # volumes:
    #   - input:/quarto/input
    #   - output:/quarto/output
