# Source: https://github.com/analythium/quarto-docker-examples/blob/main/Dockerfile.static-file

FROM bosa/quatro:20.04 AS builder

WORKDIR /quarto/output

ENTRYPOINT ["tail", "-f", "/dev/null"]

# RUN set -e -x && \
#     ls -alhR /quarto

# RUN set -e -x && \
#     quarto render /quarto/input/index.qmd --to pdf --toc

# # --------------------------------------------------------------------

# FROM ghcr.io/openfaas/of-watchdog:0.9.6 AS watchdog

# FROM alpine:latest

# RUN mkdir /app

# COPY --from=builder /app /app
# COPY --from=watchdog /fwatchdog .

# ENV mode="static"
# ENV static_path="/app"

# HEALTHCHECK --interval=3s CMD [ -e /tmp/.lock ] || exit 1

# CMD ["./fwatchdog"]
