# Source: https://github.com/analythium/quarto-docker-examples/blob/main/Dockerfile.static-file
# Updated then

FROM cavo/quatro:20.04 AS builder

WORKDIR /app

COPY input .

RUN set -e -x && \
    mkdir output && \
    quarto render index.qmd && \
    rm index.qmd

# --------------------------------------------------------------------

FROM ghcr.io/openfaas/of-watchdog:0.9.6 AS watchdog

FROM alpine:latest

RUN mkdir /app

COPY --from=builder /app /app
COPY --from=watchdog /fwatchdog .

ENV mode="static"
ENV static_path="/app"

HEALTHCHECK --interval=3s CMD [ -e /tmp/.lock ] || exit 1

CMD ["./fwatchdog"]
